<?php
/**
 * 联控模型
 * Created by PhpStorm.
 * User: borui
 * Date: 2022/2/28
 * Time: 10:47
 */

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

class Joins extends ActiveRecord
{
    public static function tableName()
    {
        return 'mj_join'; // TODO: Change the autogenerated stub
    }



    public function add($data)
    {
        $result = Yii::$app ->db -> createCommand() -> insert(self::tableName(),$data) -> execute();
        if ($result) {
            return Yii::$app ->db -> getLastInsertID();
        }else{
            return false;
        }
    }

    public function edit($data)
    {
        if ($data['id']){
            $result = Yii::$app ->db -> createCommand() -> update(self::tableName(),$data,'id='.$data['id']);
            if ($result !== fasle) {
                return true;
            }else{
                return false;
            }
        }else{
            return false;
        }
    }

    public function del($id)
    {
        $result = Yii::$app -> db -> createCommand() -> delete(self::tableName(), "id=".$id) -> execute();
        if ($result){
            return true;
        }else{
            return false;
        }
    }

}