<?php
/**
 * Created by PhpStorm.
 * User: borui
 * Date: 2022/3/1
 * Time: 16:05
 */

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

class Message extends ActiveRecord
{
    public static function tableName()
    {
        return 'mj_message'; // TODO: Change the autogenerated stub
    }

    public function add($data)
    {
        $result = Yii::$app -> db -> createCommand() -> insert(self::tableName(),$data) -> execute();
        if ($result){
            return true;
        }else{
            return false;
        }
    }

    public function edit($data)
    {
        $result = Yii::$app -> db -> createCommand() -> update(self::tableName(),$data,'id='.$data['id']) -> execute();
        if ($result){
            return true;
        }else{
            return false;
        }
    }

    public function del($id)
    {
        $result = Yii::$app -> db -> createCommand() -> delete(self::tableName(),'id='.$id) -> execute();
        if ($result){
            return true;
        }else{
            return false;
        }
    }

}