<?php
/**
 * Created by PhpStorm.
 * User: borui
 * Date: 2022/3/2
 * Time: 14:40
 */

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

class Setting extends ActiveRecord
{
    public $title;
    public static function tableName()
    {
        return 'mj_setting'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            ['title']
        ]; // TODO: Change the autogenerated stub
    }

    public function add($data)
    {
        $result = Yii::$app -> db -> createCommand() -> insert(self::tableName(),$data) -> execute();
        if ($result){
            return true;
        }else{
            return false;
        }
    }

    public function edit($data)
    {
        $result = Yii::$app -> db -> createCommand() -> update(self::tableName(),$data,'id='.$data['id']) -> execute();
        if ($result){
            return true;
        }else{
            return false;
        }
    }
}