<?php
/**
 * Created by PhpStorm.
 * User: borui
 * Date: 2022/3/7
 * Time: 16:13
 */

namespace app\models;


use yii\db\ActiveRecord;
use yii\db\Query;

class Streamrecord extends ActiveRecord
{
    public static function tableName()
    {
        return 'mj_stream_record'; // TODO: Change the autogenerated stub
    }


    public function getMonthData($gateway_id,$sid,$month,$year='')
    {
        if ($year){
            $year = $year . '-' . $month;
        }else{
            $year = date('Y',time()) . '-' . $month;
        }
        $query = new Query();
        $where = ['gateway_id' => $gateway_id, 'sid' => $sid];
        $count = $query -> from(self::tableName())
            -> where($where)
            -> andFilterWhere(['like','get_date',$year])
            -> count();
        return $count;
    }

    // 获取每日的数据流统计信息
    public function getDayData($gateway_id,$sid,$day)
    {
        $query = new Query();
        $where = ['gateway_id' => $gateway_id, 'sid' => $sid];
        $count = $query -> from(self::tableName())
            -> where($where)
            -> andFilterWhere(['like','get_date',$day])
            -> count();
        return $count;
    }

    //获取最小值
    public function getMin($sid, $where=[])
    {
        $query = new Query();
        $data = $query -> from(self::tableName()) -> where(['sid'=>$sid]) -> andFilterWhere($where) -> min('value');
//        echo $query->createCommand()->getRawSql();
        return $data;

    }

    //获取最大值
    public function getMax($sid, $where=[])
    {
        $query = new Query();
        $data = $query -> from(self::tableName()) -> where(['sid'=>$sid])  -> andFilterWhere($where) -> max('value');
        return $data;
    }

    //获取最大值
    public function getAvg($sid, $where=[])
    {
        $query = new Query();
        $data = $query -> from(self::tableName()) -> where(['sid'=>$sid]) -> andFilterWhere($where) -> average('value');
        return $data;
    }

    //获取单位
    public function getComp($sid)
    {
        $query = new Query();
        $model = new Stream();
        $data = $query -> from($model::tableName()) -> where(['id'=>$sid]) -> select(['comp']) -> one();
        return $data['comp'];
    }

    /**
     * @param $sid 数据流id
     * @param $gateway_id 网关id
     * @param $datetime 具体时间
     */
    public function getDateData($sid, $gateway_id, $datetime)
    {

    }
}