<?php
/**
 * Created by PhpStorm.
 * User: borui
 * Date: 2022/3/1
 * Time: 8:41
 */

namespace app\models;


use yii\db\ActiveRecord;
use Yii;
class Viewcontrol extends ActiveRecord
{
    public static function tableName()
    {
        return 'mj_view_control'; // TODO: Change the autogenerated stub
    }
}