<?php
/**
 * Created by PhpStorm.
 * User: borui
 * Date: 2022/3/28
 * Time: 15:58
 */

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\db\Query;

class Viewmanagejoinvideo extends ActiveRecord
{
    public static function tableName()
    {
        return 'mj_view_manage_join_video'; // TODO: Change the autogenerated stub
    }

    public function lists($vid)
    {
        $query = new Query();
        $result = $query -> from(self::tableName()) -> where(['vid' => $vid]) -> all();
        return $result;
    }
    
    public function add($data)
    {
        $result = Yii::$app -> db -> createCommand() -> insert(self::tableName(),  $data) -> execute();
        if ($result){
            return Yii::$app -> db -> getLastInsertID();
        }else{
            return false;
        }
    }

    public function edit($data)
    {
        $result = Yii::$app -> db -> createCommand() -> update(self::tableName(),  $data, 'id='.$data['id']) -> execute();
        if ($result !== false){
            return true;
        }else{
            return false;
        }
    }

    public function del($id)
    {
        $result = Yii::$app -> db -> createCommand() -> delete(self::tableName(), 'id='.$id) -> execute();
        if ($result){
            return true;
        }else{
            return false;
        }
    }
}