<?php
/**
 * 视图关联控件模型
 * Created by PhpStorm.
 * User: borui
 * Date: 2022/3/1
 * Time: 11:01
 */

namespace app\models;

use Yii;
use yii\db\ActiveRecord;

class Viewjoincontrol extends ActiveRecord
{
    public static function tableName()
    {
        return 'mj_view_join_control'; // TODO: Change the autogenerated stub
    }

    public function add($data)
    {
        $result = Yii::$app -> db -> createCommand() -> insert(self::tableName(), $data) -> execute();
        if ($result){
            return true;
        }else{
            return false;
        }
    }
}